export enum ACTIONS {
    SET_PLAY_MODE = 'SET_PLAY_MODE',
    SET_PLAY_TYPE = 'SET_PLAY_TYPE',
    SET_PLAY_ID = 'SET_PLAY_ID',
    CHANGE_VOLUME = 'CHANGE_VOLUME',
    NEXT_MUSIC = 'NEXT_MUSIC',
    PREV_MUSIC = 'PREV_MUSIC',
    CHANGE_STATUS = 'CHANGE_STATUS',
    CHANGE_PLAYLIST_INDEX = 'CHANGE_PLAYLIST_INDEX',
}
